import Jugador

j1=Jugador.cJugador("jugador1")
j2=Jugador.cJugador("jugador2")
j3=Jugador.cJugador("jugador3")
j4=Jugador.cJugador("jugador4")
j1.setMaxTantos(200)
j2.setMaxTantos(150)
judadores=(j1,j2,j3,j4)
print(j1.getMaxTantos())
print(j2.getMaxTantos())
print(j3.getMaxTantos())
print(j4.getMaxTantos())
j1.setTantos(50)
j1.setTantos(120)
j1.setTantos(20)
print(j1.getTantos())